apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-4
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
  name: app-4-service-0
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-app
    port: 16395
    protocol: TCP
    targetPort: 16395
  selector:
    app.kubernetes.io/name: app-4
  sessionAffinity: None
  type: ClusterIP
