apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    my.domain/sampleAnnotation: "annotation-data-1"
    my.domain/sampleAnnotation2: "annotation-data-2"
    my.domain/sampleAnnotation3: "annotation-data-3"
    my.domain/sampleAnnotation4: "annotation-data-4"
  labels:
    app.kubernetes.io/name: app-18
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
    my.domain/sampleLabel4: "label-data-4"
  name: app-18
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: app-18
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-18
    spec:
      containers:
      - command:
          - "bash"
          - "-c"
          - "sleep 1d"
        image: fedora:latest
        imagePullPolicy: Always
        name: my-container
        ports:

          - containerPort: 16451
            protocol: TCP
          - containerPort: 16452
            protocol: TCP
          - containerPort: 16453
            protocol: TCP
          - containerPort: 16454
            protocol: TCP

        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 20Mi
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - ALL
        #   # runAsNonRoot: true

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30