apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-12
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
  name: app-12-service-2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-app
    port: 16429
    protocol: TCP
    targetPort: 16429
  selector:
    app.kubernetes.io/name: app-12
  sessionAffinity: None
  type: ClusterIP
