apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-8
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
  name: app-8-service-3
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-app
    port: 16414
    protocol: TCP
    targetPort: 16414
  selector:
    app.kubernetes.io/name: app-8
  sessionAffinity: None
  type: ClusterIP
