apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-11
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
  name: app-11-service-2
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-app
    port: 16425
    protocol: TCP
    targetPort: 16425
  selector:
    app.kubernetes.io/name: app-11
  sessionAffinity: None
  type: ClusterIP
