apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: app-13
    my.domain/sampleLabel1: "label-data-1"
    my.domain/sampleLabel2: "label-data-2"
    my.domain/sampleLabel3: "label-data-3"
  name: app-13-service-0
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-app
    port: 16431
    protocol: TCP
    targetPort: 16431
  selector:
    app.kubernetes.io/name: app-13
  sessionAffinity: None
  type: ClusterIP
